export enum EnumType {
    TYPE_CREATE = "TYPE_CREATE",
	TYPE_UPDATE = "TYPE_UPDATE",
	TYPE_DELETE = "TYPE_DELETE",
	TYPE_COMMENT = "TYPE_COMMENT",
	TYPE_SEND_REQUEST = "TYPE_SEND_REQUEST",
	TYPE_ACCEPT_REQUEST = "TYPE_ACCEPT_REQUEST",
	TYPE_REJECT_REQUEST = "TYPE_REJECT_REQUEST",
}